// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: renderer.proto

package renderer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

type RenderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderReply) Reset() {
	*x = RenderReply{}
	mi := &file_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderReply) ProtoMessage() {}

func (x *RenderReply) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderReply.ProtoReflect.Descriptor instead.
func (*RenderReply) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderReply) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

var File_renderer_proto protoreflect.FileDescriptor

const file_renderer_proto_rawDesc = "" +
	"\n" +
	"\x0erenderer.proto\x12\brenderer\"!\n" +
	"\rRenderRequest\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\"!\n" +
	"\vRenderReply\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html2D\n" +
	"\bRenderer\x128\n" +
	"\x06Render\x12\x17.renderer.RenderRequest\x1a\x15.renderer.RenderReplyB5Z3github.com/hatena/Hatena-Intern-2025/pb/go/rendererb\x06proto3"

var (
	file_renderer_proto_rawDescOnce sync.Once
	file_renderer_proto_rawDescData []byte
)

func file_renderer_proto_rawDescGZIP() []byte {
	file_renderer_proto_rawDescOnce.Do(func() {
		file_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_renderer_proto_rawDesc), len(file_renderer_proto_rawDesc)))
	})
	return file_renderer_proto_rawDescData
}

var file_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_renderer_proto_goTypes = []any{
	(*RenderRequest)(nil), // 0: renderer.RenderRequest
	(*RenderReply)(nil),   // 1: renderer.RenderReply
}
var file_renderer_proto_depIdxs = []int32{
	0, // 0: renderer.Renderer.Render:input_type -> renderer.RenderRequest
	1, // 1: renderer.Renderer.Render:output_type -> renderer.RenderReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_renderer_proto_init() }
func file_renderer_proto_init() {
	if File_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_renderer_proto_rawDesc), len(file_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_renderer_proto_goTypes,
		DependencyIndexes: file_renderer_proto_depIdxs,
		MessageInfos:      file_renderer_proto_msgTypes,
	}.Build()
	File_renderer_proto = out.File
	file_renderer_proto_goTypes = nil
	file_renderer_proto_depIdxs = nil
}
