name: Test renderer-rust

on:
  push:
    paths:
      - .github/workflows/renderer-rust.yml
      - services/renderer-rust/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/renderer-rust

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy,rustfmt
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            services/renderer-rust

      - name: Build
        run: cargo build --locked --all-targets

      - name: Test
        run: cargo test --locked --all-features -- --nocapture

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings